---
# tasks file for secrets

# kubectl get ns - would be so much easier... but shell is bad :/
- name: Get a list of current namespace
  delegate_to: 'localhost'
  become: false
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubernetes_kubeconfig }}"
    kind: Namespace
  register: namespace_list

- name: Set Valid Namespace
  ansible.builtin.set_fact:
    valid_namespaces: "{{ lookup('template', 'valid-namespace-list.j2') }}"

- name: Print Existing Namespace
  ansible.builtin.debug:
    msg: "{{ valid_namespaces | sort }}"

- name: Debug Template
  delegate_to: 'localhost'
  become: false
  ansible.builtin.template:
    src: "secrets.yml.j2"
    dest: "scratch/debug-secrets.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  when: "kubernetes_secrets_debug"

# Create secrets from vars to k8s manifest
# This requires python3-kubernetes
- name: Create secret
  no_log: true
  delegate_to: 'localhost'
  become: false
  kubernetes.core.k8s:
    kubeconfig: "{{ kubernetes_kubeconfig }}"
    state: present
    # template: 'secrets.yml.j2', need lookup for Ansible controller’s file system
    definition: "{{ lookup('template', 'secrets.yml.j2') }}"
  when: "not kubernetes_secrets_debug"
