---
# tasks file for secrets

# Sensitive info: require explicit variable for output as opposed debug.verbosity
# - name: Debug secret
#   delegate_to: 'localhost'
#   become: false
#   ansible.builtin.debug:
#     msg: |
#       {{ (lookup('ansible.builtin.template', 'secrets.yml.j2') | to_nice_yaml).split('\n') }}
#   when: "kubernetes_secrets_debug"

- name: Debug Template
  delegate_to: 'localhost'
  become: false
  ansible.builtin.template:
    src: "secrets.yml.j2"
    dest: "scratch/debug-secrets.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  when: "kubernetes_secrets_debug"

# Create secrets from vars to k8s manifest
# This requires python3-kubernetes
- name: Create secret
  no_log: false
  delegate_to: 'localhost'
  become: false
  kubernetes.core.k8s:
    kubeconfig: "{{ kubernetes_kubeconfig }}"
    state: present
    # template: 'secrets.yml.j2', need lookup for Ansible controller’s file system
    definition: "{{ lookup('template', 'secrets.yml.j2') }}"
  when: "not kubernetes_secrets_debug"
