---
namespace: mikejonesey
name: kubernetes
version: 1.0.11
readme: README.md
authors:
  - Michael Jones <mj@mikejonesey.co.uk>
description: Install and maintenance of kubernetes clusters.
license:
  - GPL-2.0-or-later
tags: ['kubernetes', 'application', 'infrastructure', 'linux', 'tools']
dependencies:
  mikejonesey.helm_charts: ">=1.0.0"
repository: https://github.com/mikejonesey/ansible-collection-kubernetes
documentation: https://github.com/mikejonesey/ansible-collection-kubernetes/blob/main/README.md
homepage: https://github.com/mikejonesey/ansible-collection-kubernetes
issues: https://github.com/mikejonesey/ansible-collection-kubernetes/issues
build_ignore:
  - '.gitlab-ci.yml'
  - '.github/*'
  - 'roles/cis_scan'
  - 'roles/audit_webhook'
