apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: user-ro-urls
  name: user-ro-urls
rules:
  - nonResourceURLs:
      - /metrics
      - /metrics/cadvisor
      - /version
      - /healthz
      - /readyz
    verbs:
      - get
