---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: users-ro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    name: "users-ro"
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-ro-urls
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-ro-urls
subjects:
  - kind: Group
    name: "users-ro"
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-ro-nodes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-ro-nodes
subjects:
  - kind: Group
    name: "users-ro"
    apiGroup: rbac.authorization.k8s.io
