---
# defaults file for secrets

# Auth to cluster
kubernetes_kubeconfig: "/home/{{ ansible_user }}/.kube/config"

# Debug Manifest to ansible controller local file
# WARNING, setting this to true, will write sensitive data to local file
kubernetes_secrets_debug: false

# This is a list of lists to generate secrets from
kubernetes_secrets_lists:
  - kubernetes_secrets

kubernetes_secrets_create_missing_namespace: false

# Example
kubernetes_secrets:
  - name: example-docker-registry
    type: docker-registry
    namespaces:
      - default
    docker_email: "user@example.com"
    docker_password: "example"
    docker_server: "https://index.docker.io/v1/"
    docker_username: 'user'

  - name: example-generic
    type: generic
    namespaces:
      - default
    data:
      field1: "example"
      field2: "example"

  - name: example-tls
    type: tls
    namespaces:
      - default
    cert: "YWJjCg=="
    key: "YWJjCg=="
