---
##################################################
#
# example: ansible-playbook -i inventory/client/client-env.host setup.yml
#
##################################################

- name: Facts and Confirmation
  hosts: whole_environment
  become: true
  tasks:
    - name: Collect facts
      ansible.builtin.setup:
        gather_subset:
          - 'all'
    - name: Wiping Kubernetes - Destructive Action
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} will be reset"
    - name: Confirm
      ansible.builtin.pause:
  tags: facts

- name: Wipe Cluster
  hosts: '{{ k8s_target | default("k8s") }}'
  become: true
  roles:
    - name: k8s full reset
      role: mikejonesey.kubernetes.cluster_reset
      tags: reset
  tags: k8s-reset

# -------------------------------------------------
# End
# -------------------------------------------------
